# Generated by Django 3.1.7 on 2021-03-21 17:27

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('city_distr', '0002_auto_20210321_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('caregory', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, to='city_distr.rubric')),
            ],
        ),
    ]
