# Generated by Django 2.2 on 2021-03-24 19:30

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('city_distr', '0004_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='city_distr.Rubric', verbose_name='Город'),
        ),
    ]
