# Generated by Django 2.2 on 2021-03-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_distr', '0005_auto_20210324_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Район'),
        ),
    ]
