# Generated by Django 2.2 on 2021-04-05 03:50

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('city_distr', '0007_rubric_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={'verbose_name': 'Город дерево', 'verbose_name_plural': 'Города дерево'},
        ),
        migrations.AlterField(
            model_name='article',
            name='caregory',
            field=mptt.fields.TreeForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='city_distr.Rubric', verbose_name='Город'),
        ),
    ]
