# Generated by Django 2.2.19 on 2021-03-21 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'citiy',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sel_distr', models.CharField(blank=True, choices=[('1', 'Кировский'), ('2', 'Ленинский'), ('3', 'Октябрьский'), ('4', 'Свердловский'), ('5', 'Советский'), ('6', 'Центральный'), ('7', 'Железнодорожный')], max_length=15, verbose_name='Выбрать район')),
                ('cities', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Cities')),
            ],
            options={
                'verbose_name': 'Район москвы',
                'verbose_name_plural': 'Районы Москвы',
                'db_table': 'districts',
            },
        ),
    ]
