# Generated by Django 2.2.19 on 2021-03-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sel_distr', models.CharField(blank=True, choices=[('1', 'Кировский'), ('2', 'Ленинский'), ('3', 'Октябрьский'), ('4', 'Свердловский'), ('5', 'Советский'), ('6', 'Центральный'), ('7', 'Железнодорожный')], max_length=15, verbose_name='Выбрать район')),
            ],
            options={
                'verbose_name': 'Район москвы',
                'verbose_name_plural': 'Районы Москвы',
                'db_table': 'districts',
            },
        ),
        migrations.RenameModel(
            old_name='Cities',
            new_name='City',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
