# Generated by Django 2.2.19 on 2021-03-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
