# Generated by Django 2.2.19 on 2021-03-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNeighbour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('gender', models.CharField(choices=[('1', 'Выбрать'), ('2', 'Мужчина'), ('3', 'Женщина')], default='select', max_length=15, verbose_name='ВЫбрать пол')),
                ('gender_neighb', models.CharField(choices=[('1', 'Выбрать'), ('2', 'Мужчина'), ('3', 'Женщина'), ('4', 'Неважно')], default='select', max_length=15, verbose_name='Выбрать пол соседа')),
                ('sel_distr', models.CharField(choices=[('1', 'Выбрать'), ('2', 'Кировский'), ('3', 'Ленинский'), ('4', 'Октябрьский'), ('5', 'Свердловский'), ('6', 'Советский'), ('7', 'Центральный'), ('8', 'Железнодорожный')], default='select', max_length=15, verbose_name='ВЫбрать район')),
            ],
            options={
                'verbose_name': 'Сосед',
                'verbose_name_plural': 'Соседи',
                'db_table': 'neighbour',
            },
        ),
    ]
