# Generated by Django 2.2.19 on 2021-03-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createneighbour',
            name='attitude_animals',
            field=models.CharField(choices=[('1', 'положительное'), ('2', 'нейтральное'), ('3', 'отрицательное')], default='neutral', max_length=15, verbose_name='Отношение к животным'),
        ),
        migrations.AddField(
            model_name='createneighbour',
            name='presence_animals',
            field=models.CharField(blank=True, max_length=2, verbose_name='Наличие животных'),
        ),
        migrations.AddField(
            model_name='createneighbour',
            name='presence_flat',
            field=models.CharField(blank=True, max_length=2, verbose_name='Наличие квартиры'),
        ),
    ]
