# Generated by Django 2.2.19 on 2021-03-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0002_auto_20210306_1933'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='createneighbour',
            table='neighbour_rec',
        ),
    ]
