# Generated by Django 2.2.19 on 2021-03-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0003_auto_20210306_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='createneighbour',
            name='attitude_smok',
            field=models.CharField(choices=[('1', 'положительное'), ('2', 'нейтральное'), ('3', 'отрицательное')], default='neutral', max_length=15, verbose_name='Отношение к курящему'),
        ),
    ]
