# Generated by Django 2.2.19 on 2021-03-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0004_createneighbour_attitude_smok'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name_bus', models.CharField(max_length=100, verbose_name='ФИО')),
                ('category_bus', models.CharField(max_length=100, verbose_name='Категория бизнеса')),
                ('text_info_bus', models.TextField(max_length=255, verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Бизенс',
                'verbose_name_plural': 'Бизнесы',
                'db_table': 'business',
            },
        ),
        migrations.AddField(
            model_name='createneighbour',
            name='about_me',
            field=models.TextField(blank=True, max_length=255, verbose_name='О себе'),
        ),
    ]
