# Generated by Django 2.2.19 on 2021-03-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0006_auto_20210306_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createneighbour',
            name='presence_animals',
            field=models.BooleanField(default=True),
        ),
    ]
