# Generated by Django 2.2.19 on 2021-03-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0008_auto_20210306_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='createneighbour',
            name='image',
            field=models.ImageField(default='no_image_app_content.jpg', upload_to='images', verbose_name='Загрузить изображение'),
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='sel_distr',
            field=models.CharField(choices=[('1', 'Выбрать'), ('2', 'Кировский'), ('3', 'Ленинский'), ('4', 'Октябрьский'), ('5', 'Свердловский'), ('6', 'Советский'), ('7', 'Центральный'), ('8', 'Железнодорожный')], default='select', max_length=15, verbose_name='Выбрать район'),
        ),
    ]
