# Generated by Django 2.2.19 on 2021-03-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0009_auto_20210306_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbusiness',
            name='image_bus',
            field=models.ImageField(default='no_image_app_content.jpg', upload_to='images_bus', verbose_name='Загрузить изображение'),
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='about_me',
            field=models.TextField(max_length=255, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='image',
            field=models.ImageField(default='no_image_app_content.jpg', upload_to='images_n', verbose_name='Загрузить изображение'),
        ),
    ]
