# Generated by Django 2.2.19 on 2021-03-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0010_auto_20210306_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbusiness',
            name='text_info_bus',
            field=models.TextField(max_length=255, verbose_name='Информация'),
        ),
    ]
