# Generated by Django 2.2.19 on 2021-03-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0011_auto_20210307_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='createneighbour',
            name='sel_city',
            field=models.CharField(choices=[('1', 'Выбрать'), ('2', 'Москва'), ('3', 'Красноярск'), ('4', 'Ачинск'), ('5', 'Абакан'), ('6', 'Дивногорск'), ('7', 'Сосновоборск')], default='select', max_length=15, verbose_name='Выбрать город'),
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='gender',
            field=models.CharField(choices=[('1', 'Выбрать'), ('2', 'Мужчина'), ('3', 'Женщина')], default='select', max_length=15, verbose_name='Выбрать пол'),
        ),
    ]
