# Generated by Django 2.2.19 on 2021-03-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0012_auto_20210307_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createneighbour',
            name='gender_neighb',
            field=models.CharField(choices=[('1', 'Выбрать'), ('2', 'Мужчина'), ('3', 'Женщина'), ('4', 'Неважно')], default='never_mind', max_length=15, verbose_name='Выбрать пол соседа'),
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='sel_city',
            field=models.CharField(choices=[('1', 'Выбрать'), ('2', 'Москва'), ('3', 'Красноярск'), ('4', 'Ачинск'), ('5', 'Абакан'), ('6', 'Дивногорск'), ('7', 'Сосновоборск')], default='moskva', max_length=15, verbose_name='Выбрать город'),
        ),
    ]
