# Generated by Django 2.2.19 on 2021-03-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0013_auto_20210307_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createneighbour',
            name='attitude_animals',
            field=models.CharField(choices=[('1', 'положительное'), ('2', 'нейтральное'), ('3', 'отрицательное')], max_length=15, verbose_name='Отношение к животным'),
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='attitude_smok',
            field=models.CharField(choices=[('1', 'положительное'), ('2', 'нейтральное'), ('3', 'отрицательное')], max_length=15, verbose_name='Отношение к курящему'),
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='gender_neighb',
            field=models.CharField(choices=[('1', 'Выбрать'), ('2', 'Мужчина'), ('3', 'Женщина'), ('4', 'Неважно')], max_length=15, verbose_name='Выбрать пол соседа'),
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='sel_city',
            field=models.CharField(choices=[('1', 'Выбрать'), ('2', 'Москва'), ('3', 'Красноярск'), ('4', 'Ачинск'), ('5', 'Абакан'), ('6', 'Дивногорск'), ('7', 'Сосновоборск')], max_length=15, verbose_name='Выбрать город'),
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='sel_distr',
            field=models.CharField(choices=[('1', 'Выбрать'), ('2', 'Кировский'), ('3', 'Ленинский'), ('4', 'Октябрьский'), ('5', 'Свердловский'), ('6', 'Советский'), ('7', 'Центральный'), ('8', 'Железнодорожный')], max_length=15, verbose_name='Выбрать район'),
        ),
    ]
