# Generated by Django 2.2.19 on 2021-03-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0014_auto_20210307_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createneighbour',
            name='gender',
            field=models.CharField(choices=[('1', 'Выбрать'), ('2', 'Мужчина'), ('3', 'Женщина')], default='Выбрать', max_length=15, verbose_name='Выбрать пол'),
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='sel_city',
            field=models.CharField(choices=[('1', 'Выбрать'), ('1', 'Москва'), ('2', 'Красноярск'), ('3', 'Ачинск'), ('4', 'Абакан'), ('5', 'Дивногорск'), ('6', 'Сосновоборск')], max_length=15, verbose_name='Выбрать город'),
        ),
    ]
