# Generated by Django 2.2.19 on 2021-03-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0015_auto_20210307_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createneighbour',
            name='gender',
            field=models.CharField(choices=[('1', 'Мужчина'), ('2', 'Женщина')], default='Выбрать', max_length=15, verbose_name='Выбрать пол'),
        ),
    ]
