# Generated by Django 2.2.19 on 2021-03-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0019_auto_20210307_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createneighbour',
            name='gender_neighb',
            field=models.CharField(choices=[('1', 'Мужчина'), ('2', 'Женщина'), ('3', 'Неважно')], max_length=15, verbose_name='Выбрать пол соседа'),
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='sel_city',
            field=models.CharField(choices=[('1', 'Москва'), ('2', 'Красноярск'), ('3', 'Ачинск'), ('4', 'Абакан'), ('5', 'Дивногорск'), ('6', 'Сосновоборск')], max_length=15, verbose_name='Выбрать город'),
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='sel_distr',
            field=models.CharField(choices=[('1', 'Кировский'), ('2', 'Ленинский'), ('3', 'Октябрьский'), ('4', 'Свердловский'), ('5', 'Советский'), ('6', 'Центральный'), ('7', 'Железнодорожный')], max_length=15, verbose_name='Выбрать район'),
        ),
    ]
