# Generated by Django 2.2.19 on 2021-03-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0020_auto_20210307_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_first', models.CharField(blank=True, max_length=100, verbose_name='лайк!')),
                ('like_second', models.CharField(blank=True, max_length=100, verbose_name='лайк2')),
                ('date_like', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'лайк',
                'verbose_name_plural': 'лайки',
                'db_table': 'like_model',
            },
        ),
    ]
