# Generated by Django 2.2.19 on 2021-03-08 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0026_auto_20210308_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createneighbour',
            name='user_neig',
            field=models.OneToOneField(auto_created=True, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
