# Generated by Django 2.2.19 on 2021-03-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0035_auto_20210310_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='date_like',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
