# Generated by Django 2.2.19 on 2021-03-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0044_auto_20210312_0653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createneighbour',
            options={'ordering': ['-id'], 'verbose_name': 'Сосед', 'verbose_name_plural': 'Соседи'},
        ),
    ]
