# Generated by Django 2.2.19 on 2021-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0045_auto_20210312_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeBusinesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_first', models.CharField(blank=True, max_length=100, verbose_name='лайк-1')),
                ('like_second', models.CharField(blank=True, max_length=100, verbose_name='лайк-2')),
                ('date_like', models.DateField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'лайк бизнес',
                'verbose_name_plural': 'лайки бизнес',
                'db_table': 'like_busines_model',
            },
        ),
        migrations.AlterModelOptions(
            name='likemodel',
            options={'verbose_name': 'лайк', 'verbose_name_plural': 'лайки сожителей'},
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='like_first',
            field=models.CharField(blank=True, max_length=100, verbose_name='лайк1'),
        ),
    ]
