# Generated by Django 2.2.19 on 2021-03-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0046_auto_20210312_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createbusiness',
            old_name='text_info_bus',
            new_name='about_me',
        ),
        migrations.RenameField(
            model_name='createbusiness',
            old_name='image_bus',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='createbusiness',
            old_name='name_bus',
            new_name='name',
        ),
        migrations.AddField(
            model_name='createbusiness',
            name='attitude_animals',
            field=models.CharField(choices=[('1', 'положительное'), ('2', 'нейтральное'), ('3', 'отрицательное')], default='neutral', max_length=15, verbose_name='Отношение к животным'),
        ),
        migrations.AddField(
            model_name='createbusiness',
            name='attitude_smok',
            field=models.CharField(choices=[('1', 'положительное'), ('2', 'нейтральное'), ('3', 'отрицательное')], default='neutral', max_length=15, verbose_name='Отношение к курящему'),
        ),
        migrations.AddField(
            model_name='createbusiness',
            name='gender',
            field=models.CharField(choices=[('1', 'Мужчина'), ('2', 'Женщина'), ('3', 'Неважно')], default='never_mind', max_length=15, verbose_name='Выбрать пол'),
        ),
        migrations.AddField(
            model_name='createbusiness',
            name='gender_neighb',
            field=models.CharField(choices=[('1', 'Мужчина'), ('2', 'Женщина'), ('3', 'Неважно')], default='never_mind', max_length=15, verbose_name='Выбрать пол соседа'),
        ),
        migrations.AddField(
            model_name='createbusiness',
            name='presence_animals',
            field=models.BooleanField(default='0', verbose_name='Наличие животных'),
        ),
        migrations.AddField(
            model_name='createbusiness',
            name='presence_flat',
            field=models.BooleanField(default='0', verbose_name='Наличие квартиры'),
        ),
        migrations.AddField(
            model_name='createbusiness',
            name='sel_city',
            field=models.CharField(choices=[('1', 'Москва'), ('2', 'Красноярск'), ('3', 'Ачинск'), ('4', 'Абакан'), ('5', 'Дивногорск'), ('6', 'Сосновоборск')], default='', max_length=15, verbose_name='Выбрать город'),
        ),
        migrations.AddField(
            model_name='createbusiness',
            name='sel_distr',
            field=models.CharField(choices=[('1', 'Кировский'), ('2', 'Ленинский'), ('3', 'Октябрьский'), ('4', 'Свердловский'), ('5', 'Советский'), ('6', 'Центральный'), ('7', 'Железнодорожный')], default='', max_length=15, verbose_name='Выбрать район'),
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='presence_animals',
            field=models.BooleanField(verbose_name='Наличие животных'),
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='presence_flat',
            field=models.BooleanField(verbose_name='Наличие квартиры'),
        ),
    ]
