# Generated by Django 2.2.19 on 2021-03-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0049_auto_20210312_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbusiness',
            name='gender_neighb',
            field=models.CharField(choices=[('1', 'Мужчина'), ('2', 'Женщина'), ('3', 'Неважно')], max_length=15, verbose_name='Выбрать пол соседа'),
        ),
    ]
