# Generated by Django 2.2.19 on 2021-03-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0053_createbusiness_user_bus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createbusiness',
            options={'ordering': ['-id'], 'verbose_name': 'Бизенс', 'verbose_name_plural': 'Анкеты бизнес'},
        ),
        migrations.AlterModelOptions(
            name='createneighbour',
            options={'ordering': ['-id'], 'verbose_name': 'Сосед', 'verbose_name_plural': 'Анкеты соседи'},
        ),
        migrations.AddField(
            model_name='likebusinesmodel',
            name='email_first',
            field=models.CharField(blank=True, max_length=100, verbose_name='Почта хозяйна анкеты'),
        ),
        migrations.AddField(
            model_name='likebusinesmodel',
            name='email_second',
            field=models.CharField(blank=True, max_length=100, verbose_name='Почта авторизованного'),
        ),
        migrations.AddField(
            model_name='likebusinesmodel',
            name='first_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Хозяинa анкеты'),
        ),
        migrations.AddField(
            model_name='likebusinesmodel',
            name='id_ancket',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID анкеты'),
        ),
        migrations.AddField(
            model_name='likebusinesmodel',
            name='second_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Почта авторизованного'),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='email_first',
            field=models.CharField(blank=True, max_length=100, verbose_name='Почта хозяйна анкеты'),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='email_second',
            field=models.CharField(blank=True, max_length=100, verbose_name='Почта авторизованного'),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='first_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Хозяинa анкеты'),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='id_ancket',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID анкеты'),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='second_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Почта авторизованного'),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='like_first',
            field=models.CharField(blank=True, max_length=100, verbose_name='Хозяин анкеты'),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='like_second',
            field=models.CharField(blank=True, max_length=100, verbose_name='Авторизированный'),
        ),
    ]
