# Generated by Django 2.2 on 2021-03-24 19:47

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0055_allcities'),
    ]

    operations = [
        migrations.AddField(
            model_name='createneighbour',
            name='cities',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='create_profile.AllCities'),
        ),
    ]
