# Generated by Django 2.2 on 2021-03-24 19:50

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0056_createneighbour_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='createneighbour',
            name='districts_tree',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='districts_tree', to='create_profile.AllCities', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='cities',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='create_profile.AllCities', verbose_name='Город'),
        ),
    ]
