# Generated by Django 2.2 on 2021-03-25 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0059_auto_20210324_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allcities',
            options={'verbose_name': 'Город Район', 'verbose_name_plural': 'Районы'},
        ),
    ]
