# Generated by Django 2.2 on 2021-06-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0060_auto_20210325_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbusiness',
            name='cities',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='createbusiness',
            name='regin',
            field=models.CharField(blank=True, max_length=100, verbose_name='Район'),
        ),
    ]
