# Generated by Django 2.2 on 2021-07-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0061_auto_20210630_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbusiness',
            name='category_bus',
            field=models.CharField(max_length=100, unique=True, verbose_name='Категория бизнеса'),
        ),
    ]
