# Generated by Django 2.2 on 2021-07-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0062_auto_20210701_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbusiness',
            name='category_bus',
            field=models.CharField(max_length=100, verbose_name='Категория бизнеса'),
        ),
    ]
