# Generated by Django 2.2 on 2021-07-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0063_auto_20210701_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createbusiness',
            name='sel_city',
        ),
        migrations.RemoveField(
            model_name='createbusiness',
            name='sel_distr',
        ),
    ]
