# Generated by Django 2.2 on 2021-07-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0064_auto_20210701_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createneighbour',
            name='sel_city',
        ),
        migrations.RemoveField(
            model_name='createneighbour',
            name='sel_distr',
        ),
    ]
