# Generated by Django 2.2 on 2021-07-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_profile', '0065_auto_20210707_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createneighbour',
            name='districts_tree',
        ),
        migrations.AddField(
            model_name='createneighbour',
            name='regin',
            field=models.CharField(blank=True, max_length=100, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='createneighbour',
            name='cities',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
    ]
